"""Add savings goals

Revision ID: 084ae4f63e8c
Revises: ad46b8d94add
Create Date: 2026-08-19 22:25:04.522183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084ae4f63e8c'
down_revision: Union[str, Sequence[str], None] = 'ad46b8d94add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_saved', sa.Float(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goal_id'), 'savings_goal', ['id'], unique=False)
    op.create_index(op.f('ix_savings_goal_user_id'), 'savings_goal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_goal_user_id'), table_name='savings_goal')
    op.drop_index(op.f('ix_savings_goal_id'), table_name='savings_goal')
    op.drop_table('savings_goal')
    # ### end Alembic commands ###
